### PR TITLE
Fix reformed pagan ai not proselytising

### PR DESCRIPTION
**Pull request by rquinio**
- added ai_convert_other_group = 2 to reformed pagans so they proselytise
- updated graphical_culture to celticgfx for druidic (not sure if it has visible impact, but seems more coherent)

### CODE REVIEW

**Comment by Superpat** [comment]
Have you tested it ingame? Sttrange that I left it to norsegfx though, even if I'm not sure what that does.

**Comment by schwarherz** [comment]
Celticgfx looks christian, Norsegfx gives it that old-timey wooden look. It also effects the units iirc.

**Comment by rquinio** [comment]
Hmm good point, I didn't notice visual changes on my existing save, but maybe I missed them ! Maybe it needs a fresh new game ?

Searching on the forum, though the interface itself is hardcoded based on religion group, religion gfx culture may impact:
- the CoA frame on the map ?
- the temple holding icon ?
- @schwarherz from your comment, maybe also the holy order unit look ?

I'll test that tonight !

**Comment by rquinio** [comment]
Ok I can confirm that religion's graphical_culture seem only to impact the CoA frame on the map.
I didn't see any change regarding temple holdings, holy order or priest clothing.
=> norsegfx was better !

**Comment by Superpat** [comment]
Hmmm yes I agree, I'll change it back.
Edit: Oh, you've already taken care of it, thanks!

**Pull request merged**
